// Zajednička lista proizvoda (koristi je index.html i room.html)
// w/d/h = širina / dubina / visina u cm (iste mere su u 3D modelu, vidi tools/check-dims.js)
// price = cena sa formaideale.rs (redovna, 9.10.2026.); animated = model ima vrata/fioke koja se otvaraju
const products = [
  {id:'loalti', cat:'Sedenje', name:'Trosed LOALTI', price:'37.488 RSD', w:213, d:77, h:90, model:'models/loalti.glb', animated:true, arModel:'models/loalti_ar.glb', photo:'images/loalti.jpg', url:'https://formaideale.rs/artikal/trosed-loalti', desc:'Trosed u kapućino štofu sa metalnim nogama. Naslon se spušta i trosed postaje ležaj.', openLabel:'Razvuci u ležaj', closeLabel:'Vrati u trosed'},
  {id:'galaxy', cat:'Sedenje', name:'Ugaona garnitura GALAXY', price:'74.988 RSD', w:266.5, d:178, h:75, model:'models/galaxy.glb', photo:'images/card_galaxy.jpg', url:'https://formaideale.rs/artikal/ugaona-garnitura-galaxy-1', desc:'Ugaona garnitura u sivom štofu sa odvojenim jastucima za sedenje i naslon.'},
  {id:'teddy', cat:'Sedenje', name:'Fotelja TEDDY', price:'12.488 RSD', w:57.5, d:57, h:69, model:'models/teddy.glb', photo:'images/card_teddy.jpg', url:'https://formaideale.rs/artikal/fotelja-teddy', desc:'Kompaktna fotelja u tamno sivom teddy štofu sa crnim metalnim nogama.'},
  {id:'duero', cat:'Komode i police', name:'Komoda DUERO 3K2F', price:'Cena u prodavnici', w:138, d:40, h:96, model:'models/duero.glb', animated:true, arModel:'models/duero_ar.glb', photo:'images/11008303.jpg', desc:'Komoda sa troja vrata i dve fioke u dekoru hrasta.'},
  {id:'marron', cat:'Komode i police', name:'Komoda MARRON 157', price:'24.988 RSD', w:157, d:40, h:90, model:'models/marron.glb', animated:true, arModel:'models/marron_ar.glb', photo:'images/card_marron.jpg', url:'https://formaideale.rs/artikal/komoda-marron-157-3k3f3v', desc:'Komoda sa troja vrata, tri fioke i profilisanim frontom u svetloj kašmir boji.'},
  {id:'laval_tv', cat:'Komode i police', name:'TV polica LAVAL 131', price:'12.488 RSD', w:131.5, d:40, h:52, model:'models/laval_tv.glb', animated:true, arModel:'models/laval_tv_ar.glb', photo:'images/card_laval_tv.jpg', url:'https://formaideale.rs/artikal/tv-polica-laval-tv-131-2k2v', desc:'TV polica u dekoru artisan hrasta sa dva vrata i dve otvorene police.'},
  {id:'glen', cat:'Komode i police', name:'Regal GLEN', price:'22.487 RSD', w:170.5, d:41.5, h:170.5, model:'models/glen.glb', animated:true, arModel:'models/glen_ar.glb', photo:'images/card_glen.jpg', url:'https://formaideale.rs/artikal/regal-glen', desc:'Regal u kombinaciji sivog hrasta i bele boje sa otvorenim policama i zatvorenim elementima.'},
  {id:'laval_vitrina', cat:'Komode i police', name:'Vitrina LAVAL 193', price:'21.237 RSD', w:54.5, d:40, h:192.5, model:'models/laval_vitrina.glb', animated:true, arModel:'models/laval_vitrina_ar.glb', photo:'images/card_laval_vitrina.jpg', url:'https://formaideale.rs/artikal/vitrina-laval-1k-vs1-193', desc:'Visoka vitrina sa staklenim vratima i policama u dekoru artisan hrasta.'},
  {id:'oscar', cat:'Stolovi', name:'Trpezarijski sto OSCAR 160×90', price:'22.487 RSD', w:160.5, d:90.5, h:76.5, model:'models/oscar.glb', photo:'images/card_oscar.jpg', url:'https://formaideale.rs/artikal/trpezarijski-sto-oscar-ts-160x90', desc:'Veliki trpezarijski sto u dekoru artisan hrasta, za 6 do 8 osoba.'},
  {id:'sto', cat:'Stolovi', name:'Trpezarijski sto 80×80', price:'Cena u prodavnici', w:80, d:80, h:76, model:'models/sto_forma.glb', photo:'images/11008789.jpg', desc:'Kvadratni trpezarijski sto u svetlom dekoru hrasta.'},
  {id:'mohito', cat:'Stolovi', name:'Okrugli sto MOHITO fi100', price:'12.488 RSD', w:100, d:100, h:76, model:'models/mohito.glb', photo:'images/mohito.jpg', url:'https://formaideale.rs/artikal/trpezarijski-sto-mohito-fi100', desc:'Okrugli trpezarijski sto: bela metalna konstrukcija i ploča u dekoru hrasta.'},
  {id:'montese', cat:'Stolovi', name:'Klub sto MONTESE 90×50', price:'6.238 RSD', w:90, d:50, h:42.5, model:'models/montese.glb', photo:'images/card_montese.jpg', url:'https://formaideale.rs/artikal/klub-sto-montese-90x50', desc:'Klub sto sa pločom u dekoru artisan hrasta i belom konstrukcijom.'},
  {id:'simple', cat:'Stolice', name:'Trpezarijska stolica SIMPLE', price:'7.487 RSD', w:44, d:51, h:100, model:'models/simple.glb', photo:'images/simple.jpg', url:'https://formaideale.rs/artikal/trpezarijska-stolica-simple', desc:'Konzolna stolica sa visokim, prošivenim naslonom u bež štofu i metalnim postoljem.'},
  {id:'grace', cat:'Stolice', name:'Barska stolica GRACE', price:'11.238 RSD', w:54.5, d:48.5, h:101, model:'models/grace.glb', photo:'images/card_grace.jpg', url:'https://formaideale.rs/artikal/barska-stolica-grace', desc:'Barska stolica u svetlo braon štofu sa crnom metalnom konstrukcijom.'},
  {id:'nubia', cat:'Spavaća soba', name:'Krevet NUBIA 160', price:'Cena u prodavnici', w:172, d:213.5, h:102, model:'models/nubia.glb', photo:'images/11012351.jpg', desc:'Bračni krevet sa tapaciranim uzglavljem, za dušek 160 × 200 cm.'},
  {id:'hana', cat:'Spavaća soba', name:'Ormar HANA 4K2F2O', price:'42.488 RSD', w:160, d:52, h:205, model:'models/hana.glb', animated:true, arModel:'models/hana_ar.glb', photo:'images/card_hana.jpg', url:'https://formaideale.rs/artikal/ormar-hana-4k2f2o', desc:'Ormar u dekoru sonoma hrasta sa ogledalima, garderobnom šipkom, policama i dve fioke.'},
];
const fmtCm = v => String(v).replace('.', ',');
products.forEach(p => { p.dims = `${fmtCm(p.w)} × ${fmtCm(p.d)} × ${fmtCm(p.h)} cm`; });
